import { useState } from 'react';
import SecurityScoreCard from './SecurityScoreCard';
import SummaryStats from './SummaryStats';
import IssuesList from './IssuesList';
import { FilterIcon, DownloadIcon, CopyIcon, CheckmarkIcon } from './Icons';

const ResultsSection = ({ results }) => {
  const [severityFilter, setSeverityFilter] = useState('all');
  const [copied, setCopied] = useState(false);

  if (!results) return null;

  const { securityScore, overallAssessment, issues, summary } = results;

  // Filter issues based on selected severity
  const filteredIssues = severityFilter === 'all' 
    ? issues 
    : issues.filter(issue => issue.severity === severityFilter);

  // Copy report to clipboard
  const handleCopyReport = async () => {
    const reportText = `
SECURITY AUDIT REPORT
=====================

Security Score: ${securityScore}/100
Overall Assessment: ${overallAssessment}

SUMMARY
-------
Critical: ${summary.critical}
High: ${summary.high}
Medium: ${summary.medium}
Low: ${summary.low}
Total Issues: ${summary.critical + summary.high + summary.medium + summary.low}

DETAILED FINDINGS
-----------------
${issues.map((issue, idx) => `
${idx + 1}. ${issue.title} [${issue.severity.toUpperCase()}]
   ${issue.cweId ? `CWE: ${issue.cweId}` : ''}
   Description: ${issue.description}
   Lines: ${issue.lineNumbers.join(', ')}
   Recommendation: ${issue.recommendation}
`).join('\n')}

Generated by SecureCode AI
    `.trim();

    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Download report as text file
  const handleDownloadReport = () => {
    const reportText = `
SECURITY AUDIT REPORT
=====================

Security Score: ${securityScore}/100
Overall Assessment: ${overallAssessment}

SUMMARY
-------
Critical: ${summary.critical}
High: ${summary.high}
Medium: ${summary.medium}
Low: ${summary.low}
Total Issues: ${summary.critical + summary.high + summary.medium + summary.low}

DETAILED FINDINGS
-----------------
${issues.map((issue, idx) => `
${idx + 1}. ${issue.title} [${issue.severity.toUpperCase()}]
   ${issue.cweId ? `CWE: ${issue.cweId}` : ''}
   Description: ${issue.description}
   Lines: ${issue.lineNumbers.join(', ')}
   Recommendation: ${issue.recommendation}
`).join('\n')}

Generated by SecureCode AI
Date: ${new Date().toLocaleString()}
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `security-audit-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <section className="py-16 bg-background">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Security Score Card */}
        <SecurityScoreCard score={securityScore} assessment={overallAssessment} />

        {/* Summary Stats */}
        <div className="mt-8">
          <SummaryStats summary={summary} />
        </div>

        {/* Actions Bar */}
        <div className="mt-8 bg-white rounded-xl shadow-md p-4 sm:p-6 flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4">
          {/* Filter */}
          <div className="flex items-center space-x-3 w-full md:w-auto">
            <FilterIcon className="w-5 h-5 text-textSecondary flex-shrink-0" />
            <select
              value={severityFilter}
              onChange={(e) => setSeverityFilter(e.target.value)}
              className="flex-1 md:flex-initial px-4 py-3 text-sm md:text-base border-2 border-gray-200 rounded-lg focus:border-secondary focus:ring-2 focus:ring-secondary/20 transition-all cursor-pointer"
              aria-label="Filter by severity"
            >
              <option value="all">All Issues ({issues.length})</option>
              <option value="critical">Critical ({summary.critical})</option>
              <option value="high">High ({summary.high})</option>
              <option value="medium">Medium ({summary.medium})</option>
              <option value="low">Low ({summary.low})</option>
            </select>
          </div>

          {/* Export Buttons */}
          <div className="flex gap-3 w-full md:w-auto">
            <button
              onClick={handleCopyReport}
              className="flex-1 md:flex-initial flex items-center justify-center space-x-2 px-5 py-3 bg-gray-100 hover:bg-gray-200 text-primary rounded-lg font-medium transition-colors text-sm md:text-base"
              aria-label="Copy report to clipboard"
            >
              {copied ? (
                <>
                  <CheckmarkIcon className="w-5 h-5 text-accent" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <CopyIcon className="w-5 h-5" />
                  <span>Copy</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownloadReport}
              className="flex-1 md:flex-initial flex items-center justify-center space-x-2 px-5 py-3 bg-secondary hover:bg-blue-600 text-white rounded-lg font-medium transition-colors shadow-md text-sm md:text-base"
              aria-label="Download report"
            >
              <DownloadIcon className="w-5 h-5" />
              <span>Download</span>
            </button>
          </div>
        </div>

        {/* Issues List */}
        <div className="mt-10 sm:mt-12">
          <div className="mb-6 sm:mb-8">
            <h3 className="text-xl sm:text-2xl font-bold text-primary">
              {severityFilter === 'all' 
                ? 'All Issues' 
                : `${severityFilter.charAt(0).toUpperCase() + severityFilter.slice(1)} Severity Issues`}
            </h3>
            <p className="text-sm sm:text-base text-textSecondary mt-1">
              Showing {filteredIssues.length} of {issues.length} issues
            </p>
          </div>
          <IssuesList issues={filteredIssues} />
        </div>
      </div>
    </section>
  );
};

export default ResultsSection;
